<center>

# <font colour = 'red'> **FIFA 2021 Data - Data Cleaning Using Python**</font>

---

In [ ]:
from google.colab import userdata
import os

os.environ["KAGGLE_KEY"] = userdata.get('KAGGLE_KEY')
os.environ["KAGGLE_USERNAME"] = userdata.get('KAGGLE_USERNAME')

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import kaggle
# import zipfile library to extract the file downloaded from Kaggle
import zipfile

# to use regex
import re

In [ ]:
!kaggle datasets download -d yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring

Dataset URL: https://www.kaggle.com/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring
License(s): CC0-1.0
fifa-21-messy-raw-dataset-for-cleaning-exploring.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
# extracting the file from the downloaded zip
with zipfile.ZipFile('/content/fifa-21-messy-raw-dataset-for-cleaning-exploring.zip','r') as file:
    file.extractall()

In [ ]:
df = pd.read_csv('/content/fifa21 raw data v2.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   â†“OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

In [ ]:
# duplicate rows
df.duplicated().sum()

0

In [ ]:
def null_counter(x):
  col=x.columns
  print('Null values in the dataframe for each column is ')
  for i in col:

    print(f'{i} : ',x[i].isna().sum())

null_counter(df)

Null values in the dataframe for each column is
ID :  0
Name :  0
LongName :  0
Nationality :  0
Age :  0
Overall_Rating :  0
Potential :  0
Club :  0
Contract :  0
Positions :  0
Height :  0
Weight :  0
Preferred Foot :  0
BOV :  0
Best Position :  0
Joined :  0
Loan Date End :  17966
Value :  0
Wage :  0
Release Clause :  0
Attacking :  0
Crossing :  0
Finishing :  0
Heading Accuracy :  0
Short Passing :  0
Volleys :  0
Skill :  0
Dribbling :  0
Curve :  0
FK Accuracy :  0
Long Passing :  0
Ball Control :  0
Movement :  0
Acceleration :  0
Sprint Speed :  0
Agility :  0
Reactions :  0
Balance :  0
Power :  0
Shot Power :  0
Jumping :  0
Stamina :  0
Strength :  0
Long Shots :  0
Mentality :  0
Aggression :  0
Interceptions :  0
Positioning :  0
Vision :  0
Penalties :  0
Composure :  0
Defending :  0
Marking :  0
Standing Tackle :  0
Sliding Tackle :  0
Goalkeeping :  0
GK Diving :  0
GK Handling :  0
GK Kicking :  0
GK Positioning :  0
GK Reflexes :  0
Total Stats :  0
Base Stats :  0
Weak_Foot_Rating :  0
Skill_Moves_Rating :  0
A/W :  0
D/W :  0
International_Rating :  0
PAC :  0
SHO :  0
PAS :  0
DRI :  0
DEF :  0
PHY :  0
Hits :  2595
contract_start_year :  0
contract_end_year :  0

In [ ]:
df.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,â†“OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 â˜…,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 â˜…,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlÃ©tico Madrid,...,Medium,Medium,3 â˜…,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 â˜…,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 â˜…,91,85,86,94,36,59,595

In [ ]:
# from the visual it is obvious that we might not need photo and player urls for any kind of analysis so lets drop them
df.drop(columns = ['photoUrl','playerUrl'], inplace = True)

In [ ]:
df.rename( columns = {'IR' : "International_Rating",
                      'W/F' : 'Weak_Foot_Rating',
                      'SM': 'Skill_Moves_Rating',
                      'â†“OVA' : 'Overall_Rating',
                      'POT' : 'Potential'}, inplace = True)

In [ ]:
df.head(3)

,ID,Name,LongName,Nationality,Age,Overall_Rating,Potential,Club,Contract,Positions,...,A/W,D/W,International_Rating,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",...,Medium,Low,5 â˜…,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",...,High,Low,5 â˜…,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,Slovenia,27,91,93,\n\n\n\nAtlÃ©tico Madrid,2014 ~ 2023,GK,...,Medium,Medium,3 â˜…,87,92,78,90,52,90,150

In [ ]:
df['Club'].value_counts()

Club
No Club                           237
\n\n\n\nFC Barcelona               33
\n\n\n\nBurnley                    33
\n\n\n\nRC Celta                   33
\n\n\n\nTorino                     33
                                 ...
\n\n\n\nMelbourne Victory          18
\n\n\n\nBrisbane Roar              18
\n\n\n\nAdelaide United            18
\n\n\n\nPerth Glory                18
\n\n\n\nCentral Coast Mariners     18
Name: count, Length: 682, dtype: int64

In [ ]:
df2 = df.copy()

In [ ]:
df['Club'] = df["Club"].str.strip().str.replace('\n','')

In [ ]:
df['Club'].head(10)

0           FC Barcelona
1               Juventus
2        AtlÃ©tico Madrid
3        Manchester City
4    Paris Saint-Germain
5      FC Bayern MÃ¼nchen
6              Liverpool
7              Liverpool
8    Paris Saint-Germain
9           FC Barcelona
Name: Club, dtype: object

In [ ]:
df['Contract'].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 2028',
       '2010 ~ 2023', '2014 ~ 2021', '2015 ~ 2025', '2014 ~ 2026',
       '2012 ~ 2025', '2017 ~ 2020', '2002 ~ 2022', '2020 ~ 2027',
       '2013 ~ 2025', 'Dec 31, 2020 On Loan', '2019 ~ 2020',
       '2011 ~ 2025', '2016 ~ 2020', '2007 ~ 2021', '2020 ~ 2026',
       '2010 ~ 2025', '2009 ~ 2023', '2008 ~ 2021', '2020 ~ 2020',
       '2016 ~ 2026', 'Jan 30, 2021 On Loan', '2012 ~ 2020',
       '2014 ~ 2025', 'Jun 30, 2022 On Loan', '2015 ~ 2020',
       'May 31, 2021 On Loan', '2018 ~ 2020', '2014 ~ 2020',
       '2013 ~ 2020', '2006 ~ 2024', 'Jul 5, 2021 On Loan',
       'Dec 31, 2021 On Loan', '2004 ~ 2025', '2011 ~ 2020',
       'Jul 1, 2021 On Loan', 'Jan 1, 2021 On Loan', '2006 ~ 2023',
       'Aug 31, 2021 On Loan', '2006 ~ 2021', '2005 ~ 2023',
       '2003 ~ 2020', '2009 ~ 2020', '2002 ~ 2020', '2005 ~ 2020',
       '2005 ~ 2022', 'Jan 31, 2021 On Loan', '2010 ~ 2020',
       'Dec 30, 2021 On Loan', '2008 ~ 2020', '2007 ~ 2020',
       '2003 ~ 2021', 'Jun 23, 2021 On Loan', 'Jan 3, 2021 On Loan',
       'Nov 27, 2021 On Loan', '2002 ~ 2021', 'Jan 17, 2021 On Loan',
       'Jun 30, 2023 On Loan', '1998 ~ 2021', '2003 ~ 2022',
       '2007 ~ 2023', 'Jul 31, 2021 On Loan', 'Nov 22, 2020 On Loan',
       'May 31, 2022 On Loan', '2006 ~ 2020', 'Dec 30, 2020 On Loan',
       '2007 ~ 2025', 'Jan 4, 2021 On Loan', 'Nov 30, 2020 On Loan',
       '2004 ~ 2020', '2009 ~ 2025', 'Aug 1, 2021 On Loan'], dtype=object)

In [ ]:
def contract_start_year(x):
  if x == 'Free':
    return 'Free'
  elif "On Loan" in x:
    return "On Loan"
  else:
    match = re.search('(\d{4})\s*', x)
    if match:
      return match.group()
    else:
      return None
df['contract_start_year'] = df['Contract'].apply(contract_start_year)
df.head(2)

,ID,Name,LongName,Nationality,Age,Overall_Rating,Potential,Club,Contract,Positions,...,D/W,International_Rating,PAC,SHO,PAS,DRI,DEF,PHY,Hits,contract_start_year
0,158023,L. Messi,Lionel Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",...,Low,5 â˜…,85,92,91,95,38,65,771,2004
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",...,Low,5 â˜…,89,93,81,89,35,77,562,2018

In [ ]:
def contract_end_year(x):
  if x == 'Free':
    return 'Free'
  elif "On Loan" in x:
    return "On Loan"
  else:
    match = re.search('\d{4}$', x)
    if match:
      return match.group()
    else:
      return None
df['contract_end_year'] = df['Contract'].apply(contract_end_year)
df.head(2)

,ID,Name,LongName,Nationality,Age,Overall_Rating,Potential,Club,Contract,Positions,...,International_Rating,PAC,SHO,PAS,DRI,DEF,PHY,Hits,contract_start_year,contract_end_year
0,158023,L. Messi,Lionel Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",...,5 â˜…,85,92,91,95,38,65,771,2004,2021
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",...,5 â˜…,89,93,81,89,35,77,562,2018,2022

In [ ]:
df['Height'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [ ]:
df['Weight'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [ ]:
def height_to_cm(x):
  if "\'" in x:
    feet,inches = x.split("\'")
    ht = int(round(int(feet)*30.48 + int(inches.strip('"'))*2.54,0))
  else:
    ht = int(x.strip('cm'))
  return ht

df['Height'] = df['Height'].apply(height_to_cm)

In [ ]:
#since already the weight is converted to int with kgs, function will not run
def weight_to_kg(x):
  if "lbs" in x:
    weight = int(round(int(x.strip("lbs"))*0.453592 ,0))
  else:
    weight = int(x.strip('kg'))
  return weight

df['Weight'] = df['Weight'].apply(weight_to_kg)

In [ ]:
df[['Height','Weight']].head(3)

   Height  Weight
0     170      72
1     187      83
2     188      87

In [ ]:
df['International_Rating'].unique()

array(['5 â˜…', '3 â˜…', '4 â˜…', '2 â˜…', '1 â˜…'], dtype=object)

In [ ]:
df['International_Rating'] = pd.to_numeric(df['International_Rating'].str.replace('â˜…',''))

In [ ]:
df['Skill_Moves_Rating'] = pd.to_numeric(df['Skill_Moves_Rating'].str.replace('â˜…',''))
df['Weak_Foot_Rating'] = pd.to_numeric(df['Weak_Foot_Rating'].str.replace('â˜…',''))

In [ ]:
df.isna().sum()

ID                        0
Name                      0
LongName                  0
Nationality               0
Age                       0
                       ...
DEF                       0
PHY                       0
Hits                   2595
contract_start_year       0
contract_end_year         0
Length: 77, dtype: int64

In [ ]:
df.columns

Index(['ID', 'Name', 'LongName', 'Nationality', 'Age', 'Overall_Rating',
       'Potential', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'Weak_Foot_Rating', 'Skill_Moves_Rating', 'A/W', 'D/W',
       'International_Rating', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY',
       'Hits', 'contract_start_year', 'contract_end_year'],
      dtype='object')

In [ ]:
df[['Name','Club','contract_start_year','contract_start_year','contract_end_year','Joined','Loan Date End','Value', 'Wage', 'Release Clause','Hits']].head(4)

,Name,Club,contract_start_year,contract_start_year,contract_end_year,Joined,Loan Date End,Value,Wage,Release Clause,Hits
0,L. Messi,FC Barcelona,2004,2004,2021,"Jul 1, 2004",NaN,â‚¬103.5M,â‚¬560K,â‚¬138.4M,771
1,Cristiano Ronaldo,Juventus,2018,2018,2022,"Jul 10, 2018",NaN,â‚¬63M,â‚¬220K,â‚¬75.9M,562
2,J. Oblak,AtlÃ©tico Madrid,2014,2014,2023,"Jul 16, 2014",NaN,â‚¬120M,â‚¬125K,â‚¬159.4M,150
3,K. De Bruyne,Manchester City,2015,2015,2023,"Aug 30, 2015",NaN,â‚¬129M,â‚¬370K,â‚¬161M,207

In [ ]:
df['Value'].unique()

array(['â‚¬103.5M', 'â‚¬63M', 'â‚¬120M', 'â‚¬129M', 'â‚¬132M', 'â‚¬111M', 'â‚¬120.5M',
       'â‚¬102M', 'â‚¬185.5M', 'â‚¬110M', 'â‚¬113M', 'â‚¬90.5M', 'â‚¬82M', 'â‚¬17.5M',
       'â‚¬83.5M', 'â‚¬33.5M', 'â‚¬114.5M', 'â‚¬78M', 'â‚¬103M', 'â‚¬109M', 'â‚¬92M',
       'â‚¬10M', 'â‚¬76.5M', 'â‚¬89.5M', 'â‚¬87.5M', 'â‚¬79.5M', 'â‚¬124M', 'â‚¬114M',
       'â‚¬95M', 'â‚¬92.5M', 'â‚¬105.5M', 'â‚¬88.5M', 'â‚¬85M', 'â‚¬81.5M', 'â‚¬26M',
       'â‚¬21M', 'â‚¬56M', 'â‚¬67.5M', 'â‚¬53M', 'â‚¬36.5M', 'â‚¬51M', 'â‚¬65.5M',
       'â‚¬46.5M', 'â‚¬61.5M', 'â‚¬72.5M', 'â‚¬77.5M', 'â‚¬43.5M', 'â‚¬32.5M', 'â‚¬36M',
       'â‚¬32M', 'â‚¬54M', 'â‚¬49.5M', 'â‚¬57M', 'â‚¬66.5M', 'â‚¬74.5M', 'â‚¬71.5M',
       'â‚¬121M', 'â‚¬99M', 'â‚¬67M', 'â‚¬86.5M', 'â‚¬93.5M', 'â‚¬70M', 'â‚¬62M',
       'â‚¬66M', 'â‚¬58M', 'â‚¬44M', 'â‚¬81M', 'â‚¬37M', 'â‚¬14.5M', 'â‚¬46M', 'â‚¬47.5M',
       'â‚¬52.5M', 'â‚¬54.5M', 'â‚¬34.5M', 'â‚¬57.5M', 'â‚¬51.5M', 'â‚¬44.5M', 'â‚¬55M',
       'â‚¬48M', 'â‚¬60.5M', 'â‚¬63.5M', 'â‚¬61M', 'â‚¬29M', 'â‚¬58.5M', 'â‚¬55.5M',
       'â‚¬42M', 'â‚¬40.5M', 'â‚¬43M', 'â‚¬45.5M', 'â‚¬34M', 'â‚¬26.5M', 'â‚¬42.5M',
       'â‚¬35.5M', 'â‚¬45M', 'â‚¬41.5M', 'â‚¬40M', 'â‚¬11M', 'â‚¬13.5M', 'â‚¬29.5M',
       'â‚¬27M', 'â‚¬15.5M', 'â‚¬38.5M', 'â‚¬52M', 'â‚¬33M', 'â‚¬19M', 'â‚¬73.5M',
       'â‚¬38M', 'â‚¬35M', 'â‚¬47M', 'â‚¬24M', 'â‚¬30.5M', 'â‚¬18M', 'â‚¬28M', 'â‚¬25.5M',
       'â‚¬25M', 'â‚¬31M', 'â‚¬23.5M', 'â‚¬30M', 'â‚¬31.5M', 'â‚¬22.5M', 'â‚¬28.5M',
       'â‚¬4M', 'â‚¬12.5M', 'â‚¬37.5M', 'â‚¬27.5M', 'â‚¬16M', 'â‚¬15M', 'â‚¬20.5M',
       'â‚¬22M', 'â‚¬3.4M', 'â‚¬5M', 'â‚¬56.5M', 'â‚¬62.5M', 'â‚¬0', 'â‚¬39M', 'â‚¬24.5M',
       'â‚¬21.5M', 'â‚¬13M', 'â‚¬8M', 'â‚¬20M', 'â‚¬8.5M', 'â‚¬2.9M', 'â‚¬9M', 'â‚¬4.6M',
       'â‚¬50M', 'â‚¬23M', 'â‚¬18.5M', 'â‚¬7M', 'â‚¬19.5M', 'â‚¬5.5M', 'â‚¬7.5M',
       'â‚¬3.8M', 'â‚¬14M', 'â‚¬10.5M', 'â‚¬16.5M', 'â‚¬3.6M', 'â‚¬9.5M', 'â‚¬39.5M',
       'â‚¬17M', 'â‚¬12M', 'â‚¬11.5M', 'â‚¬4.9M', 'â‚¬3M', 'â‚¬1.9M', 'â‚¬6.5M',
       'â‚¬1.7M', 'â‚¬2.4M', 'â‚¬3.1M', 'â‚¬6M', 'â‚¬3.7M', 'â‚¬4.7M', 'â‚¬4.3M',
       'â‚¬2.1M', 'â‚¬1.2M', 'â‚¬1.8M', 'â‚¬4.8M', 'â‚¬3.2M', 'â‚¬1.3M', 'â‚¬825K',
       'â‚¬2.3M', 'â‚¬1.5M', 'â‚¬3.9M', 'â‚¬2.6M', 'â‚¬3.5M', 'â‚¬2.8M', 'â‚¬2.7M',
       'â‚¬4.4M', 'â‚¬4.1M', 'â‚¬950K', 'â‚¬1.6M', 'â‚¬625K', 'â‚¬1.1M', 'â‚¬4.5M',
       'â‚¬4.2M', 'â‚¬2.2M', 'â‚¬3.3M', 'â‚¬1.4M', 'â‚¬2M', 'â‚¬475K', 'â‚¬925K',
       'â‚¬750K', 'â‚¬725K', 'â‚¬2.5M', 'â‚¬1M', 'â‚¬350K', 'â‚¬525K', 'â‚¬600K',
       'â‚¬850K', 'â‚¬800K', 'â‚¬550K', 'â‚¬250K', 'â‚¬400K', 'â‚¬425K', 'â‚¬575K',
       'â‚¬210K', 'â‚¬325K', 'â‚¬900K', 'â‚¬875K', 'â‚¬650K', 'â‚¬700K', 'â‚¬500K',
       'â‚¬975K', 'â‚¬375K', 'â‚¬775K', 'â‚¬275K', 'â‚¬180K', 'â‚¬450K', 'â‚¬675K',
       'â‚¬150K', 'â‚¬240K', 'â‚¬300K', 'â‚¬130K', 'â‚¬220K', 'â‚¬200K', 'â‚¬110K',
       'â‚¬170K', 'â‚¬230K', 'â‚¬90K', 'â‚¬120K', 'â‚¬80K', 'â‚¬190K', 'â‚¬140K',
       'â‚¬160K', 'â‚¬100K', 'â‚¬60K', 'â‚¬50K', 'â‚¬70K', 'â‚¬45K', 'â‚¬35K', 'â‚¬40K',
       'â‚¬25K', 'â‚¬20K', 'â‚¬15K', 'â‚¬30K', 'â‚¬9K'], dtype=object)

In [ ]:
def value_to_euros(x):
  multipler=1
  if 'M' in x:
    multipler = 1000000
  elif 'K' in x:
    multipler = 1000
  value = x.strip('â‚¬').replace('M','').replace('K','')
  return int(float(value)*multipler)

df['Value'] = df['Value'].apply(value_to_euros)
#print(value_to_euros('â‚¬33.5M'))

In [ ]:
df['Wage'].unique()

array(['â‚¬560K', 'â‚¬220K', 'â‚¬125K', 'â‚¬370K', 'â‚¬270K', 'â‚¬240K', 'â‚¬250K',
       'â‚¬160K', 'â‚¬260K', 'â‚¬210K', 'â‚¬310K', 'â‚¬130K', 'â‚¬350K', 'â‚¬300K',
       'â‚¬190K', 'â‚¬145K', 'â‚¬195K', 'â‚¬100K', 'â‚¬140K', 'â‚¬290K', 'â‚¬82K',
       'â‚¬110K', 'â‚¬230K', 'â‚¬155K', 'â‚¬200K', 'â‚¬165K', 'â‚¬95K', 'â‚¬170K',
       'â‚¬105K', 'â‚¬115K', 'â‚¬150K', 'â‚¬135K', 'â‚¬55K', 'â‚¬58K', 'â‚¬81K', 'â‚¬34K',
       'â‚¬120K', 'â‚¬59K', 'â‚¬90K', 'â‚¬65K', 'â‚¬56K', 'â‚¬71K', 'â‚¬18K', 'â‚¬75K',
       'â‚¬47K', 'â‚¬20K', 'â‚¬84K', 'â‚¬86K', 'â‚¬74K', 'â‚¬78K', 'â‚¬27K', 'â‚¬68K',
       'â‚¬85K', 'â‚¬25K', 'â‚¬46K', 'â‚¬83K', 'â‚¬54K', 'â‚¬79K', 'â‚¬175K', 'â‚¬43K',
       'â‚¬49K', 'â‚¬45K', 'â‚¬38K', 'â‚¬41K', 'â‚¬39K', 'â‚¬23K', 'â‚¬51K', 'â‚¬50K',
       'â‚¬87K', 'â‚¬30K', 'â‚¬14K', 'â‚¬69K', 'â‚¬31K', 'â‚¬64K', 'â‚¬53K', 'â‚¬35K',
       'â‚¬21K', 'â‚¬28K', 'â‚¬17K', 'â‚¬33K', 'â‚¬70K', 'â‚¬32K', 'â‚¬89K', 'â‚¬26K',
       'â‚¬40K', 'â‚¬76K', 'â‚¬72K', 'â‚¬48K', 'â‚¬36K', 'â‚¬29K', 'â‚¬60K', 'â‚¬16K',
       'â‚¬37K', 'â‚¬24K', 'â‚¬52K', 'â‚¬0', 'â‚¬62K', 'â‚¬73K', 'â‚¬63K', 'â‚¬19K',
       'â‚¬1K', 'â‚¬66K', 'â‚¬80K', 'â‚¬12K', 'â‚¬2K', 'â‚¬42K', 'â‚¬13K', 'â‚¬900',
       'â‚¬57K', 'â‚¬77K', 'â‚¬61K', 'â‚¬22K', 'â‚¬67K', 'â‚¬44K', 'â‚¬15K', 'â‚¬11K',
       'â‚¬8K', 'â‚¬850', 'â‚¬10K', 'â‚¬88K', 'â‚¬500', 'â‚¬7K', 'â‚¬6K', 'â‚¬9K', 'â‚¬5K',
       'â‚¬700', 'â‚¬950', 'â‚¬750', 'â‚¬3K', 'â‚¬650', 'â‚¬600', 'â‚¬4K', 'â‚¬800',
       'â‚¬550'], dtype=object)

In [ ]:
def wage_to_euros(x):
    multiplier = 1
    if 'K' in x:
      multiplier = 1000
    wage = x.strip('â‚¬').replace('K','')
    return int(wage)*multiplier

df['Wage'] = df['Wage'].apply(wage_to_euros)

In [ ]:
df['Release Clause'].unique()

array(['â‚¬138.4M', 'â‚¬75.9M', 'â‚¬159.4M', ..., 'â‚¬59K', 'â‚¬35K', 'â‚¬64K'],
      dtype=object)

In [ ]:
# Function to check if a column contains 'K' or 'M'
def column_contains_K_or_M(col):
    return col.astype(str).str.contains('K|M').any()

columns_without_K_or_M = [col for col in df.columns if not column_contains_K_or_M(df['Release Clause'])]

# Display the columns
print("Columns without 'K' or 'M':", columns_without_K_or_M)

Columns without 'K' or 'M': []

In [ ]:
def rc_to_euros(x):
  multipler=1
  if 'M' in x:
    multipler = 1000000
  elif 'K' in x:
    multipler = 1000
  value = x.strip('â‚¬').replace('M','').replace('K','')
  return int(float(value)*multipler)

df['Release Clause'] = df['Release Clause'].apply(rc_to_euros)
#print(rc_to_euros('â‚¬59K'))

In [ ]:
df['Release Clause'].head(3)

0    138400000
1     75900000
2    159400000
Name: Release Clause, dtype: int64

In [ ]:
df.rename(columns= {'Value' : 'Value (Euros)','Release Clause' : 'Release Clause (Euros)','Wage' : 'Wage (Euros)'}, inplace = True)

In [ ]:
df['Loan Date End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

In [ ]:
pd.to_datetime('Jan 4, 2021').dt.date

AttributeError: 'Timestamp' object has no attribute 'dt'

In [ ]:
df['Joined'].unique()

array(['Jul 1, 2004', 'Jul 10, 2018', 'Jul 16, 2014', ..., 'Sep 22, 2018',
       'Feb 28, 2015', 'Mar 6, 2018'], dtype=object)

In [ ]:
df2['date_column2'] = pd.to_datetime(df['Loan Date End'], format='%b %d, %Y').dt.date

In [ ]:
df2['date_column2'].unique()

array([NaT, datetime.date(2021, 6, 30), datetime.date(2020, 12, 31),
       datetime.date(2021, 1, 30), datetime.date(2022, 6, 30),
       datetime.date(2021, 5, 31), datetime.date(2021, 7, 5),
       datetime.date(2021, 12, 31), datetime.date(2021, 7, 1),
       datetime.date(2021, 1, 1), datetime.date(2021, 8, 31),
       datetime.date(2021, 1, 31), datetime.date(2021, 12, 30),
       datetime.date(2021, 6, 23), datetime.date(2021, 1, 3),
       datetime.date(2021, 11, 27), datetime.date(2021, 1, 17),
       datetime.date(2023, 6, 30), datetime.date(2021, 7, 31),
       datetime.date(2020, 11, 22), datetime.date(2022, 5, 31),
       datetime.date(2020, 12, 30), datetime.date(2021, 1, 4),
       datetime.date(2020, 11, 30), datetime.date(2021, 8, 1)],
      dtype=object)

In [ ]:
df2[df2['date_column2'] == 'datetime.date(2021, 6, 30)']

Empty DataFrame
Columns: [ID, Name, LongName, Nationality, Age, Overall_Rating, Potential, Club, Contract, Positions, Height, Weight, Preferred Foot, BOV, Best Position, Joined, Loan Date End, Value, Wage, Release Clause, Attacking, Crossing, Finishing, Heading Accuracy, Short Passing, Volleys, Skill, Dribbling, Curve, FK Accuracy, Long Passing, Ball Control, Movement, Acceleration, Sprint Speed, Agility, Reactions, Balance, Power, Shot Power, Jumping, Stamina, Strength, Long Shots, Mentality, Aggression, Interceptions, Positioning, Vision, Penalties, Composure, Defending, Marking, Standing Tackle, Sliding Tackle, Goalkeeping, GK Diving, GK Handling, GK Kicking, GK Positioning, GK Reflexes, Total Stats, Base Stats, Weak_Foot_Rating, Skill_Moves_Rating, A/W, D/W, International_Rating, PAC, SHO, PAS, DRI, DEF, PHY, Hits, date_column, date_column2]
Index: []

[0 rows x 77 columns]